### PR TITLE
fix: make android requests async

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Previously the Requests on Android were blocking the UI Thread as they were executed synchronously, this PR makes the request to be executed async.

@josephbaylon can you please run the E2E tests for Android?

### CODE REVIEW

**Comment by josephbaylon** [comment]
@enahum When I try to build android using `npm run android` from `example`, I'm getting this compilation error

```
> Task :mattermost.networkclient:compileDebugKotlin FAILED
e: /Users/josephbaylon/Projects/original/react-native-network-client/android/src/main/java/com/mattermost/networkclient/NetworkClient.kt: (94, 83): Unresolved reference: Promise
e: /Users/josephbaylon/Projects/original/react-native-network-client/android/src/main/java/com/mattermost/networkclient/NetworkClient.kt: (145, 51): Unresolved reference: IOException
```

**Comment by enahum** [comment]
Let me fix that

**Comment by enahum** [comment]
@josephbaylon should be fixed now

**Comment by josephbaylon** [comment]
@enahum I'm having trouble completing the `npm run android`. Not sure if you're able to locally. I also tried `npm start -- --reset-cache`, but the same results. I'm getting the following,

```
error Cannot find module 'metro-config/src/defaults/blacklist'
Require stack:
- /Users/josephbaylon/Projects/original/react-native-network-client/example/metro.config.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/import-fresh/index.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/cosmiconfig/dist/loaders.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/cosmiconfig/dist/index.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/tools/config/readConfigFromDisk.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/tools/config/index.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/commands/install/install.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/commands/index.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/index.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/bin.js.
Error: Cannot find module 'metro-config/src/defaults/blacklist'
Require stack:
- /Users/josephbaylon/Projects/original/react-native-network-client/example/metro.config.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/import-fresh/index.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/cosmiconfig/dist/loaders.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/cosmiconfig/dist/index.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/tools/config/readConfigFromDisk.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/tools/config/index.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/commands/install/install.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/commands/index.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/index.js
- /Users/josephbaylon/Projects/original/react-native-network-client/example/node_modules/@react-native-community/cli/build/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/josephbaylon/Projects/original/react-native-network-client/example/metro.config.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
```

**Comment by enahum** [comment]
Is not related to this PR, I believe it broke with the deps updates.. I'll fix it with this PR, will need a few minutes though

**Comment by enahum** [comment]
@josephbaylon let's try again.. I've tested that the app loads on my device

**Review by josephbaylon — APPROVED** [review]
LGTM. I ran the tests and re-ran the ones that were flaky and they were passing. There are moments though that the app would crash with `System UI Not responding` and I had to manually test the scenario, which passed. Not sure if the changes are causing the app to crash intermittently but I doubt it.

**Comment by enahum** [comment]
Not sure why the app stopped responding, it certainly does not look like caused by this PR :/

**Comment by enahum** [comment]
@shazm can you please review this asap?

Thanks

**Comment by josephbaylon** [comment]
Also, fixed e2e expectations and pushed to this branch

**Review by enahum — COMMENTED** [review]
Great

**Review by shazm — APPROVED** [review]
All looks good to me - just had to mess around and get the right combo of node/npm (v7/v16) versions to get it all to play nice, I can build and make requests 👍 

Sidenote - JS seems to have gone back to 2-space tabs rather than 4, I believe it's 4-space tabs through out the TS files.

**Pull request merged**
