### PR TITLE
[MM-30523] Validate configuration options

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
Created Zod schemas for `APIClientConfiguration` and `RequestOptions` then used the provided `safeParse()` function to validate the configuration/options. If the invalid keys/values are found, we `console.warn` the error.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30523

### CODE REVIEW

**Review by enahum — APPROVED** [review]
this seems so useful!

**Comment by josephbaylon** [comment]
@migbot I'm getting a warning bubble from the app regarding Require Cycle. Even if I dismiss it once, the bubble comes up again whenever the app is launched. Detox is unable to tap on the dismiss button and e2e tests fail because some of the elements at the bottom are blocked. Please look into so that the warning is not shown on the app but shown on the console only.

|Collapsed|Expanded|
|:---|:---|
|Screen Shot 2021-04-09 at 2 23 27 PM|Screen Shot 2021-04-09 at 2 23 40 PM|

**Review by josephbaylon — APPROVED** [review]
LGTM. All tests passed.

Screen Shot 2021-04-09 at 3 57 49 PM

**Pull request merged**
