### PR TITLE
fix crash on Android when default locale format numbers with comma

### PR DESCRIPTION
**Pull request by vovkasm**
#### Summary
This fixed crash on Android with non english numeric locale.

See this SO answer and corresponding question: https://stackoverflow.com/a/49432344

### CODE REVIEW

**Comment by enahum** [comment]
Hey @vovkasm thanks for this a couple of questions:
1. Would you mind signing the CLA so we can eventually merge this PR
2. What do you think about this suggestion instead of your approach
```kotlin
// 2-Decimal places, rounded up
private val df = DecimalFormat("#.00")
    .apply{
        roundingMode = RoundingMode.UP
        decimalFormatSymbols = DecimalFormatSymbols(Locale.US)
    }
```

**Comment by vovkasm** [comment]
@enahum 

> 1. Would you mind signing the CLA so we can eventually merge this PR

Yes, I would like to!

> What do you think about this suggestion instead of your approach

I think that using complex formatting and parsing algorithms for just for rounding numbers are not the most efficient use of mobile processor resources ;-)

**Review by enahum — APPROVED** [review]

**Comment by enahum** [comment]
@avinashlng1080 can you make sure this PR is merged and the reference in the mobile app is updated once @vovkasm signs the CLA?

Thanks.

**Pull request merged**
